# Site settings
title: Allegheny Biosciences
description: Making Drug Discovery Accessible to Everyone
url: "https://alleghenybio.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - README.md
  - LICENSE
